site_name: Parse Plugin - V2
site_url: http://parse-corona-sdk-plugin.readthedocs.org
site_author: C. Byerley - develephant
copyright: 2015 &copy; develephant | coronium.io
markdown_extensions:
  - smarty
  - fenced_code
  - codehilite:
      noclasses: True
      guess_lang: True
      pygments_style: borland
  - toc:
      permalink: True
pages:
  - Corona SDK Parse Plugin - V2: index.md
  - Developer Guide:
      - Chapter 1: CH1_Usage.md
      - Chapter 2: CH2_Usage.md
      - Chapter 3: CH3_Usage.md
      - Chapter 4: CH4_Usage.md
      - Chapter 5: CH5_Usage.md
  - API:
      - Analytics: API_Analytics.md
      - Apps: API_Apps.md
