site_name: Parse Corona Plugin - V2
site_url: http://parse.develephant.com
site_author: Chris Byerley
copyright: Parse plugin for Corona SDK - &copy;2015 Chris Byerley - @develephant
markdown_extensions:
  - admonition
  - smarty
  - fenced_code
  - codehilite:
      noclasses: True
      guess_lang: True
      pygments_style: borland
  - toc:
      permalink: True
pages:
  - Corona SDK Parse Plugin - V2: index.md
  - Developer Guide:
      - Chapter 1: CH1_Usage.md
      - Chapter 2: CH2_Usage.md
      - Chapter 3: CH3_Usage.md
      - Chapter 4: CH4_Usage.md
      - Chapter 5: CH5_Usage.md
  - Plugin API:
      - Analytics: API_Analytics.md
      - Apps: API_Apps.md
      - Cloud: API_Cloud.md
      - Config: API_Config.md
      - Files: API_Files.md
      - Hooks: API_Hooks.md
      - Installations: API_Installations.md
      - Objects: API_Objects.md
      - Push: API_Push.md
      - Roles: API_Roles.md
      - Schemas: API_Schemas.md
      - Sessions: API_Sessions.md
      - Triggers: API_Triggers.md
      - Users: API_Users.md
  - About Plugin: About.md
