site_name: Parse Plugin - V2
site_url: http://parse-corona-sdk-plugin.readthedocs.org
copyright: C. Byerley | 2015 &copy; develephant | coronium.io
pages:
  - Start Here...: index.md
  - Development: Overview.md
markdown_extensions:
  - smarty
  - fenced_code
  - codehilite:
      guess_lang: False
      noclasses: True
      pygments_style: manni
  - toc:
      permalink: True
